language: python

python:
  - 2.6
  - 2.7
  - 3.0

install: "pip install -r _scripts/requirements.txt --use-mirrors"

script: nosetests -vw _scripts

matrix:
  allow_failures:
    - python: 2.6
    - python: 3.0